// examples/vue/javascript/advanced/src/App.vue
<!--
/**
 * @author Saki
 * @date 2019-04-21 19:02:52
 * @Last Modified by: Saki
 * @Last Modified time: 2019-04-23 12:37:16
 */
-->
<template>
    <div id="container">
        <app-header title="Gantt Advanced Vue demo"></app-header>
        <app-panel></app-panel>
    </div>
</template>

<script>
    import 'bryntum-gantt/gantt.stockholm.css';
    import AppHeader from './components/header/Header.vue';
    import AppPanel from './components/Panel.vue';

    export default {
        name: 'app',

        components: {
            AppHeader,
            AppPanel
        } // eo components
    } // eo export default App

</script>

<style lang="scss">
    @import './App.scss';
</style>

<!-- eof -->

// examples/react/javascript/advanced/src/App.js
/**
 * @author Saki
 * @date 2019-04-19 18:36:38
 * @Last Modified by: Saki
 * @Last Modified time: 2019-04-19 21:48:41
 * 
 * The App file. It should stay as simple as possible 
 */

// libraries
import React from 'react';

// our stuff
import 'bryntum-react-shared/resources/shared.scss';
import './App.scss';
import Main from './containers/Main';

const app = props => (<Main />);

export default app;

// eof
