// examples/vue/javascript/advanced/src/App.vue
<!--
/**
 * @author Saki
 * @date 2019-04-21 19:02:52
 * @Last Modified by: Saki
 * @Last Modified time: 2019-04-23 12:37:16
 */
-->
<template>
    <div id="container">
        <app-header title="Gantt Advanced Vue demo"></app-header>
        <app-panel></app-panel>
    </div>
</template>

<script>
    import 'bryntum-gantt/gantt.stockholm.css';
    import AppHeader from './components/header/Header.vue';
    import AppPanel from './components/Panel.vue';

    export default {
        name: 'app',

        components: {
            AppHeader,
            AppPanel
        } // eo components
    } // eo export default App

</script>

<style lang="scss">
    @import './App.scss';
</style>

<!-- eof -->

// examples/angular/taskeditor/src/app/app.component.ts
/**
 * @author Saki
 * @date 2019-05-22 18:21:57
 * @Last Modified by: Saki
 * @Last Modified time: 2019-06-27 09:51:21
 */
import { Component, OnInit } from '@angular/core';
import ganttConfig from './ganttConfig';

@Component({
    selector    : 'app-root',
    templateUrl : './app.component.html',
    styleUrls   : ['./app.component.scss']
})
export class AppComponent implements OnInit{

    title = 'Task editor customization Angular demo';
    ganttConfig = ganttConfig;

    ngOnInit(): void {
    } // eo function ngOnInit

} // eo class AppComponent

// eof

<!-- 
/**
 * @author Saki
 * @date 2019-05-22 16:10:15
 * @Last Modified by: Saki
 * @Last Modified time: 2019-06-27 09:50:50
 */
-->
<header>
    <h1><a href="../../../../">Task editor customization Angular demo</a></h1>
    
    <bry-fullscreen></bry-fullscreen>
</header>
<bry-gantt
    #gantt
    [columns]  = "ganttConfig.columns"
    [project]  = "ganttConfig.project"
    [taskEdit] = "ganttConfig.features.taskEdit"
></bry-gantt>

<!-- eof -->
