// examples/angular/_shared/projects/bryntum-angular-shared/src/lib/fullscreen.component.ts
/**
 * Angular wrapper for Bryntum Fullscreen button
 */

/* <remove-on-release> */
/* cSpell: ignore toggleable */
/* </remove-on-release> */

import { Component, OnInit, OnDestroy, ElementRef } from '@angular/core';
// UMD bundle is used to support IE11 browser. If you don't need it just use "import { ... } from 'bryntum-gantt'" instead
import { Fullscreen, WidgetHelper } from 'bryntum-gantt/gantt.umd.js';

@Component({
    selector : 'bry-fullscreen',
    template : ''
})

export class FullscreenComponent implements OnInit, OnDestroy {

    // class variables
    private elementRef : ElementRef;
    private button : any;

    /**
     * Saves element to have container to render the button to
     * @param element
     */
    constructor(element : ElementRef) {
        this.elementRef = element;
    }

    /**
     * Runs once on component init. Creates and renders Bryntum Button
     */
    ngOnInit() {
        if (!Fullscreen.enabled) {
            return;
        }
        const button = WidgetHelper.createWidget({
            type       : 'button',
            appendTo   : this.elementRef.nativeElement,
            icon       : 'b-icon b-icon-fullscreen',
            tooltip    : 'Fullscreen',
            toggleable : true,
            cls        : 'b-blue b-raised',
            onToggle   : ({ pressed }) => {
                if (pressed) {
                    Fullscreen.request(document.documentElement);
                } else {
                    Fullscreen.exit();
                }
            }
        });

        Fullscreen.onFullscreenChange(() => {
            button['pressed'] = Fullscreen.isFullscreen;
        });

        this.button = button;

    }

    /**
     * Destroys the Bryntum button
     */
    ngOnDestroy() {
        if (this.button) {
            this.button.destroy();
        }
    }

}

// examples/react/javascript/advanced/src/components/header/Fullscreen.js
/**
 * @author Saki
 * @date 2019-03-16 17:46:34
 * @Last Modified by: Saki
 * @Last Modified time: 2019-04-28 21:09:10
 *
 * Fullscreen button. If container is passed in props then it
 * appends itself to that container. Otherwise it creates a
 * div and renders into that div.
 */
/*  */

// libraries
import React, { useRef, useEffect } from 'react';
import { Fullscreen, WidgetHelper } from 'bryntum-gantt';

const button = props => {

    // refs and t function
    const
        elRef = useRef(),
        buttonRef = useRef();

    // Bryntum button instance
    const button = buttonRef.current = buttonRef.current || (Fullscreen.enabled ? WidgetHelper.createWidget({
        type       : 'button',
        id         : 'fullscreen-button',
        icon       : 'b-icon b-icon-fullscreen',
        tooltip    : 'Fullscreen',
        toggleable : true,
        cls        : 'b-blue b-raised',
        onToggle   : ({ pressed }) => {
            if (pressed) {
                Fullscreen.request(document.documentElement);
            }
            else {
                Fullscreen.exit();
            }
        }
    }) : null);

    // runs once on mounting – initialization
    useEffect(() => {
        if (button) {
            Fullscreen.onFullscreenChange(() => {
                button.pressed = Fullscreen.isFullscreen;
            });

            button.appendTo = props.container || elRef.current;
            if (!props.skipRender) {
                button.render();
            }
        }

        return () => {
            if (button) {
                Fullscreen.onFullscreenChange(null);
            }
        };

    }, []);

    // container for the button
    return props.container ? null : <div ref={elRef}></div>;

}; // eo function button

// connects to Redux and exports the button
export default button;

// eof
